# Metadata
title: "Rashmika Kolleri!"
description: "I’m an interactive web developer, hacker, and social engineer. Here's something interesting I worked on!"
keywords: ["web developer", "designer", "jekyll", "hacker", "NIT Warangal", "CybSec"]
domain: "https://rashmika.me"

# Third party services
# (Anything you put here will be public!)
google-analytics:
github: "starlight43/starlight43.github.io"
branch: "master"
glitch: "Rashmika"

# Rubygems
# (The ones used for this site breaks GitHub Pages)
plugins:
  - jekyll-archives
  - jekyll-default-layout
  - jekyll-auto-image
  - jekyll-postfiles

# Build settings
encoding: utf-8
markdown: kramdown
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"

# Permalinks
permalink: /:title/

# Tags
jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    tag: '/hashtag/:name/'
